### ISSUE TITLE
Is it possible to add image to header?

### ISSUE THREAD

**Issue by garyganyang** [guyonroche/exceljs#293] opened 2017-03-23 10:55 UTC
Hi guys, 
i want to add watermarks to excel,  i found that xlsxwriter(python) can do it easily by setting an image to header like `worksheet.set_header('&C&G', {'image_left': 'logo.jpg','margin': 4})`, 
then you can see it in “Page View/Layout” mode by setting pageView like `worksheet.set_page_view()`.

can this exceljs do the same thing? im longing for that, , many thanks in advance.

**Comment by Rycochet** [comment] 2017-03-23 11:33
Duplicate of #173, #156 and #34 - searching first is useful...

**Closed** 2017-03-24 02:45 UTC

**Comment by bldulam1** [comment] 2022-11-22 06:00
what is the current status to this? is it not yet possible?

I saw in the README that it is not yet supported
