### ISSUE TITLE
Failed to open an excel file

### ISSUE THREAD

**Issue by gm2008** [guyonroche/exceljs#186] opened 2016-09-23 15:01 UTC
Hello, 
   I'm just trying to load an excel file using exceljs and have got the following error: 

```
C:\Users\user_name\load_excel\node_modules\exceljs\lib\xlsx\xform\sheet\row-xform.js:97
      var spans = node.attributes.spans.split(':').map(function(span) { return parseInt(span); });
                                       ^
TypeError: Cannot read property 'split' of undefined
    at utils.inherits.parseOpen (C:\Users\user_name\load_excel\node_modules\exceljs\lib\xlsx\xform\sheet\row-xform.js:97:40)
    at utils.inherits.parseOpen (C:\Users\user_name\load_excel\node_modules\exceljs\lib\xlsx\xform\list-xform.js:74:31)
    at utils.inherits.parseOpen (C:\Users\user_name\load_excel\node_modules\exceljs\lib\xlsx\xform\sheet\worksheet-xform.js:129:19)
    at SAXStream.<anonymous> (C:\Users\user_name\load_excel\node_modules\exceljs\lib\xlsx\xform\base-xform.js:65:14)
    at emitOne (events.js:77:13)
    at SAXStream.emit (events.js:169:7)
    at Object.me._parser.(anonymous function) [as onopentag] (C:\Users\user_name\load_excel\node_modules\exceljs\node_modules\sax\lib\
sax.js:245:15)
    at emit (C:\Users\user_name\load_excel\node_modules\exceljs\node_modules\sax\lib\sax.js:615:33)
    at emitNode (C:\Users\user_name\load_excel\node_modules\exceljs\node_modules\sax\lib\sax.js:620:3)
    at openTag (C:\Users\user_name\load_excel\node_modules\exceljs\node_modules\sax\lib\sax.js:801:3)
    at Object.write (C:\Users\user_name\load_excel\node_modules\exceljs\node_modules\sax\lib\sax.js:1261:31)
    at SAXStream.write (C:\Users\user_name\load_excel\node_modules\exceljs\node_modules\sax\lib\sax.js:227:16)
    at Entry.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)
    at Entry.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

    The excel file was originally created by `excel-builder.js`, it can be opened by MS Excel normally.

**Comment by guyonroche** [comment] 2016-10-25 07:53
Closing as this is duplicate of #163

**Closed by guyonroche** 2016-10-25 07:53 UTC
